### ISSUE TITLE
Remove footer text next to logo

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proud-theme#1]
Think we should keep the footer logo area simple and just have the image.

![footer](https://cloud.githubusercontent.com/assets/1569463/12693714/6d6de1e6-c6c7-11e5-8e37-730630f1b88a.png)

**Comment by kevindherman** [comment]
Erika mentioned this in our call that this fell out of their branding guidelines, going with Luke's suggestion will help avoid that issue with other cities.
